### ISSUE TITLE
custom config

### ISSUE THREAD

**Issue by donnie-dominguez** [Sabuto/hassio-repo#6]
When I create a custom telegraf.conf and put it in /share/ by using the 'Samba share' add-on it removes the config file after starting. The file works like I expect it to work, but it is removed, and after a restart of Telegraf it doesn't have the custom config anymore. This means that I have to copy the file every time I restart Telegraf. What do I do wrong?

**Comment by Sabuto** [comment]
this will be because i have made it so it moves the file instead of copying it I overlooked that part, I will update and re-release tomorrow hopefully.

**Comment by donnie-dominguez** [comment]
Thanks!

**Comment by Sabuto** [comment]
0.5.4 should fix this :)
