### ISSUE TITLE
Updating Telegraf add on kills home assistant install

### ISSUE THREAD

**Issue by foxy82** [Sabuto/hassio-repo#9]
Hey thanks for the add on it is really useful.

I've just tried to update from 0.5.6 to 0.5.7 and it completely kills my Home Assistant box - supervisor seems to crash and I lose SSH access. After a while the supervisor seems to come back but SSH remains down until I reboot.

It is very strange not much other info - has anyone else reported this?

**Comment by Sabuto** [comment]
Hmm that's very strange, no one else has reported this. Literally the only difference between the two versions is that i change the startup value in the config as the old one was deprecated.

**Comment by foxy82** [comment]
When the supervisor came back up it didn't restart any add ons. Doing an upgrade there worked. 

I then had to reboot the box (using the supervisor) to get ssh back. I'm using native ssh on the Debian OS and not an add on. Strange and unexpectedly brutal but looks like it is back now and upgraded so there is a workaround as such closing this as I expect it isn't going to be easy to reproduce.

**Comment by Sabuto** [comment]
> 
> 
> When the supervisor came back up it didn't restart any add ons. Doing an upgrade there worked.
> 
> I then had to reboot the box (using the supervisor) to get ssh back. I'm using native ssh on the Debian OS and not an add on. Strange and unexpectedly brutal but looks like it is back now and upgraded so there is a workaround as such closing this as I expect it isn't going to be easy to reproduce.

sorry for the late response, but i did a new release and it has fixed the issue
